mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zimo.demo.bean
  configuration:
    map-underscore-to-camel-case:  true
mapper:
  mappers: com.zimo.demo.mybatis.TkMapper
  identity: MYSQL
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://172.20.81.28:3306/stu_tea?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: hanyu123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.20.81.28
    port: 6379
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql